apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: my-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app
status:
  loadBalancer: {}